logger_level = 2
run_dig = False
use_reals = False
use_random_seed = False
prove_term = False
prove_nonterm = False
max_nonterm_refinement_depth = 3
n_inps = 2
inps_threshold = 2
test_ratio = 0.2
SOLVER_TIMEOUT = 5 * 1000 # 5s